version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calidadWeb_reestructuracion
    ports:
      - "8105:80"                  
    volumes:
      - ./:/var/www/html    
   # depends_on: 
   # - db
    networks:
      - red_local
      
volumes:
  db_data:

networks:
  red_local:
